### ISSUE TITLE
cant compile with 5.9.X version

### ISSUE THREAD

**Issue by lc09cn** [multiOTP/multiOTPCredentialProvider#65]
i try some versions.

and I can compile 5.8.1.1 but cant compile 5.9.x 。
this is the log:
已启动生成…
1>------ 已启动生成: 项目: CppClientCore, 配置: Debug Win32 ------
2>------ 已启动生成: 项目: Shared, 配置: Debug Win32 ------
1>Endpoint.cpp
2>Shared.cpp
2>D:\www\multiOTPCredentialProvider-5.9.2.1\Shared\Shared.cpp(23,10): fatal error C1083: 无法打开包括文件: “Logger.h”: No such file or directory
2>已完成生成项目“Shared.vcxproj”的操作 - 失败。
1>D:\www\multiOTPCredentialProvider-5.9.2.1\CppClientCore\CppClientCore\Endpoint.cpp(149,2): error C4996: 'GetVersionExW': 被声明为已否决
1>Logger.cpp
1>MultiOTPRegistryReader.cpp
1>正在生成代码...
1>已完成生成项目“CppClientCore.vcxproj”的操作 - 失败。
3>------ 已启动生成: 项目: CredentialProvider, 配置: Debug Win32 ------
3>Configuration.cpp
3>D:\www\multiOTPCredentialProvider-5.9.2.1\CredentialProvider\Configuration.h(21,10): fatal error C1083: 无法打开包括文件: “PIConf.h”: No such file or directory
3>CCredential.cpp
3>D:\www\multiOTPCredentialProvider-5.9.2.1\CredentialProvider\Utilities.h(2,10): fatal error C1083: 无法打开包括文件: “MultiOTPConfiguration.h”: No such file or directory
3>CProvider.cpp
3>D:\www\multiOTPCredentialProvider-5.9.2.1\CredentialProvider\Utilities.h(2,10): fatal error C1083: 无法打开包括文件: “MultiOTPConfiguration.h”: No such file or directory
3>Dll.cpp
3>Utilities.cpp
3>D:\www\multiOTPCredentialProvider-5.9.2.1\CredentialProvider\Utilities.h(2,10): fatal error C1083: 无法打开包括文件: “MultiOTPConfiguration.h”: No such file or directory
3>正在生成代码...
3>已完成生成项目“CredentialProvider.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 3 个，最新 0 个，跳过 0 个 ==========

**Comment by multiOTP** [comment]
Hello,
have you tried to compile it in 64bits, release mode ?
Best regards
